version: '3'

services:
  mysqldb:
    image: mysql:5.7
    networks:
      - gestion-station-ski-network
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_DATABASE=gestion-station-ski:1.0
    restart: unless-stopped


  gestion-station-ski:
    image: croccodevops/hamzaski:1.0
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/gestion-station-ski?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "0000"
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
    networks:
      -         gestion-station-ski-network
    stdin_open: true
    tty: true

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

  nexus:
    image: sonatype/nexus3
    ports:
      - "8082:8082"
    networks:
      - sonarnet

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"

networks:
  sonarnet:
  gestion-station-ski-network:
    driver: bridge

volumes:
  db:
  sonarqube_data:
  sonarqube_extensions:
